"""update classes

Revision ID: 28cb5d15c850
Revises: 432a0dc50c53
Create Date: 2020-09-23 19:45:15.998350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cb5d15c850'
down_revision = '432a0dc50c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pitches', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'owner_id')
    # ### end Alembic commands ###
