"""update classes

Revision ID: 432a0dc50c53
Revises: 8235147d49ea
Create Date: 2020-09-23 19:42:38.844320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432a0dc50c53'
down_revision = '8235147d49ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_pitches_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'pitches_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitches_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_pitches_id_fkey', 'users', 'pitches', ['pitches_id'], ['id'])
    # ### end Alembic commands ###
