"""add comments

Revision ID: 8235147d49ea
Revises: 724c32c7ec60
Create Date: 2020-09-23 19:37:13.280169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8235147d49ea'
down_revision = '724c32c7ec60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('downvote', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upvote', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('comments_owner_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.drop_column('comments', 'body')
    op.drop_column('comments', 'owner_id')
    op.drop_column('pitches', 'upvotes')
    op.drop_column('pitches', 'downvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_owner_id_fkey', 'comments', 'users', ['owner_id'], ['id'])
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'description')
    op.drop_table('upvotes')
    op.drop_table('downvotes')
    # ### end Alembic commands ###
